### PR TITLE
Fix a case where img alt detection could cause real content to be del…

### PR DESCRIPTION
**Pull request by froodian**
…eted if there was an img tag without alt on the same line as one with alt

### CODE REVIEW

**Comment by froodian** [comment]
This required forking premailer, obviously.  I've also submitted this as a pull to them directly - if/once they accept that, we can go back to the main fork.

**Comment by froodian** [comment]
(Fixes https://github.com/Appboy/platform/issues/15779)

**Review by dlu306090 — APPROVED** [review]
Ohhh, nice. :) I didn't realize we could change this file cause it's in the gem -- just wondering if you upgraded the gem, or if in the future we upgrade we'll have to migrate this change over?

**Comment by dlu306090** [comment]
Oh just kidding, I should have read your comments. Okay, all sounds good!

**Comment by froodian** [comment]
no worries - yeah I'll be submitting a platform pull in a sec to point to this fork instead of the main one

**Pull request merged**
